name: Build All MapIDs

on: [workflow_dispatch]

jobs:
    first_job:
        name: First Job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Requirements
              run: pip install requirements.txt

            - name: Validate Install
              run: pkg-config vips --modversion
    

        