name: Build Latest MapIDs

on: [workflow_dispatch, push]

jobs:
    fetch-cache:
      name: Build Latest Wiki Maps
      runs-on: ubuntu-22.04

      steps:
        - name: 1. Install Python
          uses: actions/setup-python@v5
          with: 
            python-version: '3.12'
        - name: check
          run: python --version

        - name: 2. Checkout
          uses: actions/checkout@v4
          
        - name: 10. Install vips
          run: |
            sudo apt update
            sudo apt-get install libvips-dev --no-install-recommends

        - name: 3. Install Requirements
          run: |
            python --version
            pip install -r requirements.txt

        - name: 4. Download Latest Cache
          run: |
            python scripts/buildWikiMaps.py getCache
            CACHE_VER=$(cat lastVersion.txt)
            echo "CACHE_VER=$CACHE_VER" >> $GITHUB_ENV

        - name: 5. Checkout RuneLite
          run: |
            git clone https://github.com/runelite/runelite.git RuneLite

        - name: 6. Set up JDK 11
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 11

        - name: 7. Build RuneLite
          run: |
            cd RuneLite
            mvn install -q -f pom.xml -DskipTests

        - name: 8. Build MapExport
          run: |
            mvn -q clean package
    
        - name: 9. Run MapExport
          working-directory: ./osrs-wiki-maps
          run: |
            java -jar target/osrs-wiki-maps-1.10.26-shaded.jar $CACHE_VER
        


        - name: 10. Generate Base Tiles
          run: |
            python scripts/buildWikiMaps.py createBaseTiles $CACHE_VER

        - name: 11. Build All MapID Tiles
          run: |
            python scripts/buildWikiMaps.py buildAllMapIDs $CACHE_VER

        - name: 12. Timestamp Release
          id: tag
          run: |
            echo "::set-output name=release_tag::WikiMapGen_$(date +"%Y.%m.%d_%H-%M")"
            echo "::set-output name=release_count::${{github.run_number}}"

        - name: 13. Package and Release
          uses: softprops/action-gh-release@v2
          with:
            name: ${{env.CACHE_VER}}
            tag_name: ${{steps.tag.outputs.release_tag}}
            body: |
              Release No. ${{steps.tag.outputs.release_count}}
              Using openRS2 Cache $CACHE_VER
            token: ${{secrets.GITHUB_TOKEN}}
            files: osrs-wiki-maps/out/mapgen/versions/${{env.CACHE_VER}}/tiles/rendered
            make_latest: true